[providers]
python = true

[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["python -m venv /app/.venv", "/app/.venv/bin/pip install -r requirements.txt"]

[start]
cmd = "/app/.venv/bin/python cipher_bot.py"
